services:
  nginx:
    build: ./nginx
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./wp:/var/www/html
      - ./plugins:/var/www/html/wp-content/plugins
    networks:
      - kwc-net
  php:
    build: ./php
    volumes:
      - ./wp:/var/www/html
      - ./plugins:/var/www/html/wp-content/plugins
    networks:
      - kwc-net
  redis:
    image: redis:alpine
    networks:
      - kwc-net
  mysql:
    image: mysql
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - kwc-net
networks:
  kwc-net:
    driver: "bridge"
volumes:
  mysqldata:
    driver: "local"